### ISSUE TITLE
support multiple examples

### ISSUE THREAD

**Issue by scriptacus** [cesarferreira/dryrun#10]
Some repositories contain multiple example apps.  As far as I can see, there's no way to tell dryrun which app to install/launch, and not all example apps are installed.

Example repository:
https://github.com/konmik/nucleus

**Comment by ivan-leschinsky** [comment]
@cesarferreira  With this PR (https://github.com/cesarferreira/dryrun/pull/13 it could be something like:

``` shell
dryrun https://github.com/konmik/nucleus -m nucleus-example-with-fragments
```

**Comment by cesarferreira** [comment]
@scriptacus just merged @ivan-leschinsky's PR, works awesome ;) give it a try
