### ISSUE TITLE
An option to run all android tests

### ISSUE THREAD

**Issue by ghostbuster91** [cesarferreira/dryrun#101]
Hi,

Is there an option to dryrun all android tests?

**Comment by cesarferreira** [comment]
hi, nope there isn't

**Comment by ghostbuster91** [comment]
Ok, but would it be possible to add it?
The second question is, whether we should or not?
What do you think about it?

**Comment by cesarferreira** [comment]
Yep, it's possible to add, instead of installing the app, run the tests, feel free to open a pull request
