### ISSUE TITLE
Can I install with Homebrew?

### ISSUE THREAD

**Issue by rnitame** [cesarferreira/dryrun#102]
I will create pull request to Homebrew/homebrew-core

**Comment by cesarferreira** [comment]
Can you show me the pr link?

**Comment by rnitame** [comment]
@cesarferreira 
https://github.com/Homebrew/homebrew-core/pull/20400

**Comment by cesarferreira** [comment]
thanks, let me know when it's merged so I can add it to the README.md

**Comment by rnitame** [comment]
OK!
