### ISSUE TITLE
can't run in macOS Hight Sierra 10.13.1

### ISSUE THREAD

**Issue by navyifanr** [cesarferreira/dryrun#103]
In macOS Hight Sierra 10.13.1, input `dryrun https://github.com/cesarferreira/android-helloworld` in terminal, ouput the information:
```
-bash: /usr/local/bin/dryrun: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: 
bad interpreter: No such file or directory
```

So, I run the command `ruby -version`, it shows:
```
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
-e:1:in `<main>': undefined local variable or method `rsion' for main:Object (NameError)
```

I don't know whether it's concerned with the ruby's version or macOS' version...

**Comment by cesarferreira** [comment]
It's showing 2 different versions of Ruby, please reinstall your Ruby. Use rbenv or rvm
