### ISSUE TITLE
Dryrun failed to install on window

### ISSUE THREAD

**Issue by tunlinnaung** [cesarferreira/dryrun#105]
I have this error when I try to install "gem install dryrun" on my machine.
Please help to figure out why I failed to install?

```
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing dryrun:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-ll-2.1.2/ext/
c
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20171222-5100-d0nk7c.rb extconf.rb
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-ll-2.1.2/ext/c
make "DESTDIR=" clean

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-ll-2.1.2/ext/c
make "DESTDIR="
generating libll-x64-mingw32.def
make: *** No rule to make target `/C/Ruby24-x64/include/ruby-2.4.0/ruby.h', need
ed by `driver.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-l
l-2.1.2 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0
/ruby-ll-2.1.2/gem_make.out
```

**Comment by tunlinnaung** [comment]
@cesarferreira Please help?

**Comment by cesarferreira** [comment]
Hey, I haven't touched any windows machine in like 5 years now, have no idea of how to help you mate, sorry.

Are you sure you have your SDK and stuff all configured like it's explained in the readme?

**Comment by tunlinnaung** [comment]
Sorry to say that I failed since "gem install dryrun" from readme.
I tried to solve by googling. But can't help me.

May I know how about to install from Mac?

**Comment by cesarferreira** [comment]
in mac you just run `gem install dryrun` and it all should work

**Comment by luispereira** [comment]
Also, long time without touching any windows machine, let me try to help you: 

First you have to install ruby and ruby DevKit (you have tutorials in how to install them on ruby website)

If everything is ok (`ruby -v` will know if ruby is correctly installed for example) then just use `gem install dryrun`
Then, depending on your machine there might be some errors during the process, but I can try help you from this point onwards
