### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by WahdanZ** [cesarferreira/dryrun#11]
FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':app'.
  
  > failed to find target with hash string 'android-23' in: /Users/ahmedwahdan/Downloads/adt-bundle-mac-x86_64-20140702/sdk
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6 mins 58.472 secs
Installing github.cesarferreira.helloworld...
executing: adb shell am start -n "github.cesarferreira.helloworld/github.cesarferreira.helloworld.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER

Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=github.cesarferreira.helloworld/.MainActivity }
Error type 3
Error: Activity class {github.cesarferreira.helloworld/github.cesarferreira.helloworld.MainActivity} does not exist.

> If you want to remove the app you just installed, execute:

**Comment by WahdanZ** [comment]
can i change compileSdkVersion before instal app

**Comment by cesarferreira** [comment]
`dryrun` is not prepared to do that....
But you can just have your android-sdk up to date and have no problems :wink:
