### ISSUE TITLE
Message: "Your Dryrun version is outdated, want to update? [Y/n]:"

### ISSUE THREAD

**Issue by amanzan** [cesarferreira/dryrun#110]
I constantly get this message, every time I run dryrun. Even after entering Y, it keeps appearing next time. I even installed again dryrun but still same message.

Any way to get rid of it?

**Comment by cesarferreira** [comment]
I think I know why it's happening, I'll fix it today, thanks for pointing it out

**Comment by cesarferreira** [comment]
should be fixed, let me know if it's not

**Comment by amanzan** [comment]
All good now, thanks a lot! dryrun is amazing :)

**Comment by cesarferreira** [comment]
Thanks man, glad you enjoy it
