### ISSUE TITLE
Saying "No" to auto-update updates dryrun anyway

### ISSUE THREAD

**Issue by ghostbuster91** [cesarferreira/dryrun#113]

**Comment by cesarferreira** [comment]
Can't see why

![image](https://user-images.githubusercontent.com/277426/37256836-2ee94216-2558-11e8-831c-b5419bc2e7d2.png)

Does anything here look suspicious?

**Comment by ghostbuster91** [comment]
No, but devil lays in details :) 
Take a look at those two functions: http://ruby-doc.org/core-2.4.0/String.html#method-i-casecmp
