### ISSUE TITLE
Set default gradle and change default download dir?

### ISSUE THREAD

**Issue by TheMaxCoder** [cesarferreira/dryrun#119]
Hi César!

First of all thanks for the brilliant idea and great work :) 
Currently, it checks the `gradle-wrapper.properties` file and download that version of `gradle` if it's not already downloaded.
I usually always download the latest `gradle` and use it in Android Studio and I was wondering if I could do the same with `dryrun`?
I just downloaded two sample projects and it downloads the `gradle` each time so it would be great if we can avoid that.

and please tell me how can I change the default download temp folder to some other destination on `windows`? if that's possible.

Again thanks for the great work!
Max

**Comment by cesarferreira** [comment]
Hello,
thanks for the compliment.

You should not download the latest gradle, your project needs the wrapper, the latest gradle might not work with a given project.

If you downloaded 2 projects and they have the same gradle version, gradle will not be downloaded again.

It's not possible to change the location for the temp folder, feel free to open a pull request with that feature if you really want it.

Thanks

**Comment by TheMaxCoder** [comment]
Oh okay got it 
Unfortunately, I'm not a Ruby developer so making any changes would not be possible for me :)

**Comment by cesarferreira** [comment]
I'm not a ruby dev either :)
