### ISSUE TITLE
How to fixed it ? 

### ISSUE THREAD

**Issue by kazimdsaidul** [cesarferreira/dryrun#122]
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory - /platform-tools/adb (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open3.rb:95:in `popen3'
	from /Library/Ruby/Gems/2.3.0/gems/dryrun-1.1.6/lib/dryrun/dryrun_utils.rb:54:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/dryrun-1.1.6/lib/dryrun/dryrun_utils.rb:46:in `run_adb'
	from /Library/Ruby/Gems/2.3.0/gems/dryrun-1.1.6/lib/dryrun.rb:115:in `pick_device'
	from /Library/Ruby/Gems/2.3.0/gems/dryrun-1.1.6/lib/dryrun.rb:175:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/dryrun-1.1.6/bin/dryrun:6:in `<top (required)>'
	from /usr/local/bin/dryrun:22:in `load'
	from /usr/local/bin/dryrun:22:in `<main>'

**Comment by cesarferreira** [comment]
`No such file or directory - /platform-tools/adb `
you clearly don't have the android sdk in your system PATH
