### ISSUE TITLE
ERROR:  While executing gem ... (Gem::FilePermissionError)

### ISSUE THREAD

**Issue by hussainabbas** [cesarferreira/dryrun#125]
hello brother 
i am having an issue while installing dryrun.
ERROR:  While executing gem ... (Gem::FilePermissionError)

**Comment by cesarferreira** [comment]
That's a problem with your computer, not `dryrun`

**Comment by khawarcheema** [comment]
okay bruh......
any solution ?

**Comment by hussainabbas** [comment]
okay bro any solution?

**Comment by cesarferreira** [comment]
probably a faulty ruby installation, do `brew install ruby` and it should be fixed
