### ISSUE TITLE
Failed to install dryrun on windows

### ISSUE THREAD

**Issue by xSuperMu** [cesarferreira/dryrun#126]
After executing the command "gem install dryrun" on my windows machine, with the latest Ruby version
I got this error

**ERROR:  While executing gem ... (ArgumentError)
    wrong number of arguments (given 1, expected 0)**

Can you help me?

**Comment by xSuperMu** [comment]
Is it still unavailable on the Windows platform?

**Comment by cesarferreira** [comment]
Yes, and unless someone opens a pull request, it will not be supported
