### ISSUE TITLE
Can't install on mac

### ISSUE THREAD

**Issue by kobeumut** [cesarferreira/dryrun#129]
I think that's error of rjb library. 
While I install dry run I get an error
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/umutadali/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rjb-1.6.1/COPYING

<img width="811" alt="image" src="https://user-images.githubusercontent.com/5182289/63211076-19948980-c0fb-11e9-9f6b-f658089286ba.png">

**Comment by cesarferreira** [comment]
that's not related to dryrun, just google the error https://stackoverflow.com/questions/17550903/why-do-i-get-a-permission-denied-error-while-installing-a-gem
