### ISSUE TITLE
Stopped working after updating to Mac OS Catalina

### ISSUE THREAD

**Issue by amanzan** [cesarferreira/dryrun#130]
I'm getting this error after updating to Catalina:

```
-bash: /usr/local/bin/dryrun: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory
```
Googled it and tried several stuff but none of them worked for dryrun :(
Any idea?

Thanks in advance

**Comment by cesarferreira** [comment]
I'm using Catalina and it works, you probably need to reinstall your ruby.
You're using a very old version of ruby by the way.

This is not an issue with dryrun so i'll close the issue.

**Comment by amanzan** [comment]
Sorry but I don't even have that ruby version installed. Is it possible that somewhere in the code you are "defaulting" to that version, and that causes the problem? I tried everything that came to my mind, including reinstalling, and problem still persists. Didn't do anything special, just moving to Catalina, and suddenly dryrun just stopped working. I'm seeing people having this problem with cocoapods, fastlane, etc. Tried all the solutions listed but still unable to make it work

**Comment by amanzan** [comment]
After trying everything I could find (cleaning up PATH, installing rbenv, deleting everything pointing to the old 2.3 version...), the only thing that fixed the issue was reinstall dryrun like this:
```gem install dryrun -n /usr/local/bin```

Leaving this here in case it helps anyone. Man this was annoying...

**Comment by cesarferreira** [comment]
you can take a look at my gemspec, I doesn't look like I specify anything.
https://github.com/cesarferreira/dryrun/blob/master/dryrun.gemspec 

Glad you fixed it!
