### ISSUE TITLE
Facing problem on Windows 10

### ISSUE THREAD

**Issue by sudarshan103** [cesarferreira/dryrun#131]
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:319:in `check_for_activated_spec!
': You have already activated highline 2.0.2, but your Gemfile requires highline 1.7.10. Prepending `bundle e
xec` to your command may solve this. (Gem::LoadError)

on used bundle exec : 

C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:462:in `block in rep
lace_bin_path': can't find executable dryrun for gem dryrun. dryrun is not currently included in the bundle,
perhaps you meant to add it to your Gemfile? (Gem::Exception)

**Comment by cesarferreira** [comment]
I don't support windows but if you want to open a pull request I'll accept it :)
