### ISSUE TITLE
where is dryrun installed?

### ISSUE THREAD

**Issue by vj68** [cesarferreira/dryrun#133]
![dryrun-error](https://user-images.githubusercontent.com/26388709/72620516-7247a700-3965-11ea-886c-1a38a4ffa0f7.png)

**Comment by cesarferreira** [comment]
![image](https://user-images.githubusercontent.com/277426/72690655-6bac6180-3b16-11ea-8c20-45e9ffd035a3.png)

maybe your ruby installation is faulty. This tool is up for 5 years now and no one complained before

**Comment by vj68** [comment]
Solved it

Had to add `/home/rajvijay/.gem/bin` to PATH.

`export PATH=$PATH:"/home/rajvijay/.gem/bin"`
