### ISSUE TITLE
dryrun totally does not work

### ISSUE THREAD

**Issue by aido93** [cesarferreira/dryrun#135]
Dryrun fails after some successful attempts of usage:
```
$ dryrun -v # or dryrun -h, or dryrun ., or dryrun https://github.com/cesarferreira/android-helloworld
Traceback (most recent call last):
	15: from /usr/local/bin/dryrun:23:in `<main>'
	14: from /usr/local/bin/dryrun:23:in `load'
	13: from /var/lib/gems/2.5.0/gems/dryrun-1.2.1/bin/dryrun:6:in `<top (required)>'
	12: from /var/lib/gems/2.5.0/gems/dryrun-1.2.1/bin/dryrun:6:in `new'
	11: from /var/lib/gems/2.5.0/gems/dryrun-1.2.1/lib/dryrun.rb:18:in `initialize'
	10: from /var/lib/gems/2.5.0/gems/dryrun-1.2.1/lib/dryrun.rb:89:in `outdated_verification'
	 9: from /var/lib/gems/2.5.0/gems/dryrun-1.2.1/lib/dryrun/dryrun_utils.rb:39:in `up_to_date'
	 8: from /var/lib/gems/2.5.0/gems/dryrun-1.2.1/lib/dryrun/dryrun_utils.rb:30:in `latest_version'
	 7: from /usr/lib/ruby/2.5.0/open-uri.rb:35:in `open'
	 6: from /usr/lib/ruby/2.5.0/open-uri.rb:735:in `open'
	 5: from /usr/lib/ruby/2.5.0/open-uri.rb:165:in `open_uri'
	 4: from /usr/lib/ruby/2.5.0/open-uri.rb:224:in `open_loop'
	 3: from /usr/lib/ruby/2.5.0/open-uri.rb:224:in `catch'
	 2: from /usr/lib/ruby/2.5.0/open-uri.rb:226:in `block in open_loop'
	 1: from /usr/lib/ruby/2.5.0/open-uri.rb:755:in `buffer_open'
```

**Comment by cesarferreira** [comment]
![image](https://user-images.githubusercontent.com/277426/78542786-98a41280-77ef-11ea-9ff1-b5ffff384b92.png)

which OS are you on?

**Comment by aido93** [comment]
Ubuntu 18.04

But I found out that github.com was not available then. My hotfix was to hardcode version of dryrun:
```
#file: /var/lib/gems/2.5.0/gems/dryrun-1.2.1/lib/dryrun/dryrun_utils.rb
      url = 'https://raw.githubusercontent.com/cesarferreira/dryrun/master/lib/dryrun/version.rb'
      #url ='/var/lib/gems/2.5.0/gems/dryrun-1.2.1/lib/dryrun.rb'
```

Maybe it is not good idea to check new version availability on startup. Could you change default behaviour and add cli-key for update dryrun on startup?

**Comment by cesarferreira** [comment]
what do you mean by cli key?

**Comment by aido93** [comment]
Command line interface (cli) key:
`dryrun -key`

**Comment by yanglilizhang** [comment]
I also encountered the same problem, how to solve it? I'm on win10 and I always fail ，I want to use this   @cesarferreira thanks

run:dryrun git@github.com:google/cameraview.git
result：
Traceback (most recent call last):
        23: from E:/my_software/dryrun/Ruby26-x64/bin/dryrun:23:in `<main>'
        22: from E:/my_software/dryrun/Ruby26-x64/bin/dryrun:23:in `load'
        21: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dryrun-1.2.1/bin/dryrun:6:in `<top (required)>'
        20: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dryrun-1.2.1/bin/dryrun:6:in `new'
        19: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dryrun-1.2.1/lib/dryrun.rb:18:in `initialize'
        18: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dryrun-1.2.1/lib/dryrun.rb:89:in `outdated_verification'
        17: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dryrun-1.2.1/lib/dryrun/dryrun_utils.rb:39:in `up_to_date'
        16: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dryrun-1.2.1/lib/dryrun/dryrun_utils.rb:26:in `latest_version'
        15: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:35:in `open'
        14: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:736:in `open'
        13: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
        12: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
        11: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
        10: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
         9: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
         8: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:337:in `open_http'
         7: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:919:in `start'
         6: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
         5: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:945:in `connect'
         4: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
         3: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
         2: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
         1: from E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:947:in `open'
E:/my_software/dryrun/Ruby26-x64/lib/ruby/2.6.0/net/http.rb:947:in `initialize': getaddrinfo: 请求的名称有效，但是找不到请求的类型的数据。  (SocketError)

**Comment by cesarferreira** [comment]
@yanglilizhang if it works on windows is a coincidence because i built this tool for macOS, in your case, the error says "socketError" so I'm assuming you're behind a firewall

**Comment by yanglilizhang** [comment]
> @yanglilizhang if it works on windows is a coincidence because i built this tool for macOS, in your case, the error says "socketError" so I'm assuming you're behind a firewall

thanks
