### ISSUE TITLE
run on ubuntu14.04  show error 

### ISSUE THREAD

**Issue by suncunhu** [cesarferreira/dryrun#14]
The dryrun is cool :+1: 
follow README.md  , I installed  dryrun in ubuntu .
use ruby version is ruby2.0.0p384 

but show an error :

![dryrun](https://cloud.githubusercontent.com/assets/9711417/10481776/9b446d4a-72a5-11e5-9840-0ec7bfc0378d.png)

sorry ,  I do not understand ruby script    - - !

I hope you can solve this problem , thank you .

**Comment by cesarferreira** [comment]
this looks like a replicate of #3 , do you confirm?

**Comment by suncunhu** [comment]
well , now  it  run  in my phone 
1. i need change the build.gradle ,  i can not update my android sdk to android api 23 .
   
   compileSdkVersion 21
   buildToolsVersion "21.1.2"
2. run   ./gradlew clean assemble installDebug

Thank you  :)

**Comment by cesarferreira** [comment]
So your problem was that you didn't have API 23? 
it works now?

**Comment by suncunhu** [comment]
Yes , It works now . This ruby script is no problem . 

I am chinese , 
Because Internet censorship , Update  android sdk  is  difficult ,
I have to use VPN to update android sdk ..............

**Comment by cesarferreira** [comment]
@suncunhu wow mate, had no idea it was that bad, glad to hear that you like **dryrun** and that you managed to get it to work ;)
