### ISSUE TITLE
Run with stacktrace doesn't work

### ISSUE THREAD

**Issue by jonibatista** [cesarferreira/dryrun#15]
Great work sir! 

But how can I run with --stacktrace, --info or --debug? It isn't working for me.

Cheers

**Comment by cesarferreira** [comment]
Thanks mate,
That is not implemented, if you really need it you can make a pull request, it should be pretty straight forward. 

Something like:

``` ruby
opts.on('-s', '--stacktrace', 'Enables stacktrace') do |flag|
  @stacktrace_enabled = true
end
```
