### ISSUE TITLE
Failed on Linux

### ISSUE THREAD

**Issue by taojunpo** [cesarferreira/dryrun#17]
I'm a Linux user, after completing all the options in the [README.md](https://github.com/cesarferreira/dryrun/blob/master/README.md)
`gem install dryrun`
`dryrun git@github.com:cesarferreira/android-helloworld.git`
After getting the project cloned, the terminal prints

```
gradlew: 158: gradlew: Syntax error: "(" unexpected
Failed
```

then got stuck

**Comment by cesarferreira** [comment]
do this:

```
git clone git@github.com:cesarferreira/android-helloworld.git
cd android-helloworld
./gradlew assembleDebug
```

What happens?

**Comment by joaogouveia** [comment]
I'm with the same issue.

Running like you asked, worked... but using dryrun I got the same error on ununtu

**Comment by cesarferreira** [comment]
this is a duplicate, check #3
