### ISSUE TITLE
Whether can only be used for MAC

### ISSUE THREAD

**Issue by tmexcept** [cesarferreira/dryrun#20]

**Comment by cesarferreira** [comment]
is this a question?

**Comment by tmexcept** [comment]
I thinked,yes.
I used Windows,and, don't know how to use this.Maybe,you can show me,how to use with Windows?
Thanks!

**Comment by tmexcept** [comment]
Sorry, i just want to know how to use it with Windows.
And,i don't know how do with 

> 5.Import the project you just downloaded
> 6.Sync gradle
> 7.Run the project

**Comment by cesarferreira** [comment]
Sorry mate, it only works on OSX and Linux.
if you or someone in the community wants to make a pull request with that feature, feel welcome :)
