### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Shajeel-Afzal** [cesarferreira/dryrun#21]
I got the following error while installing it. 

``` java
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```

Any solution please?

**Comment by TheLester** [comment]
@Shajeel-Afzal maybe you should change permissions of this dir? Did you run command with sudo ?

**Comment by cesarferreira** [comment]
Yeah man, just google the error, it's not related to dryrun.
Here's a solution:
http://stackoverflow.com/questions/14607193/installing-gem-or-updating-rubygems-fails-with-permissions-error
