### ISSUE TITLE
(NameError)

### ISSUE THREAD

**Issue by zekapp** [cesarferreira/dryrun#23]
Which ruby version do we need to use? I having error while running this comand "dryrun https://github.com/cesarferreira/android-helloworld"

```
/usr/local/lib/ruby/gems/2.3.0/gems/dryrun-0.5.4/lib/dryrun/github.rb:15:in `get_destination': uninitialized constant DryRun::Github::Digest (NameError)
    from /usr/local/lib/ruby/gems/2.3.0/gems/dryrun-0.5.4/lib/dryrun/github.rb:11:in `initialize'
    from /usr/local/lib/ruby/gems/2.3.0/gems/dryrun-0.5.4/lib/dryrun.rb:85:in `new'
    from /usr/local/lib/ruby/gems/2.3.0/gems/dryrun-0.5.4/lib/dryrun.rb:85:in `call'
    from /usr/local/lib/ruby/gems/2.3.0/gems/dryrun-0.5.4/bin/dryrun:5:in `<top (required)>'
    from /usr/local/bin/dryrun:23:in `load'
```

My ruby environment

`ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`

**Comment by cesarferreira** [comment]
Hey mate!
just released a new version, please do a `gem install dryrun` for it to update to `0.5.6`

let me know if it worked! :)

Cheers!

**Comment by zekapp** [comment]
Thanks 

It works :)

**Comment by cesarferreira** [comment]
Awesome, thanks for letting me know!
