### ISSUE TITLE
Keeps saying I need to set ANDROID_HOME

### ISSUE THREAD

**Issue by bytehala** [cesarferreira/dryrun#24]
It's already set on ~/.bashrc and I even restarted my Mac, but still does not work.

If there are any diagnostic steps I can take to help resolve this, please let me know.

**Comment by cesarferreira** [comment]
if you type: `echo $ANDROID_HOME` does it show the path?

**Comment by bytehala** [comment]
Sorry, yeah I forgot to mention I tried that, and it does not.
I was low on willpower last night, so I did not try `~/.bash_profile`
Setting it on `~/.bash_profile` solved it. Thanks.

**Comment by cesarferreira** [comment]
No problem mate, if anything happens let me know so I can fix it
