### ISSUE TITLE
cannot use proxy for gradle

### ISSUE THREAD

**Issue by mohammadrafigh** [cesarferreira/dryrun#25]
thanks for your great job,

I want to request a feature if it's not exists already. I want to add http and https proxy for gradle when fetching dependencies but I can not find any option.

**Comment by cesarferreira** [comment]
Hey, thanks for the compliment.
You mean provide a proxy because you can't access maven?

**Comment by mohammadrafigh** [comment]
unfortunately some maven and gradle repositories have restrictions in my country.

**Comment by cesarferreira** [comment]
Aw ok, so that will happen whenever you use Gradle, you should try to find an alternative solution like changing your DNS's to the google ones or openDNS so you can solve your problem forever ;)
Don't get me wrong but that's not quite dryrun's problem so to speak.
Best of luck and say something when you find a solution 👍

**Comment by mohammadrafigh** [comment]
umm... ok I know but it would be much better if you could include a gradle.properties when you want to run gradle build command which includes:

```
systemProp.https.proxyHost=user entered host
systemProp.https.proxyPort=user entered port
systemProp.http.proxyHost=user entered host
systemProp.http.proxyPort=user entered port
```

I thought it would be easy. otherwise thanks again for your fast reply.

**Comment by cesarferreira** [comment]
Didn't know about this, so you're saying that if I add a gradle.properties with this:

```
systemProp.http.proxyHost=www.somehost.org
systemProp.http.proxyPort=8080
systemProp.http.proxyUser=userid
systemProp.http.proxyPassword=password
```

it will work for you?

**Comment by mohammadrafigh** [comment]
Yes sure, in my case I use polipo so i use it like this without username and pass

```
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=8123
systemProp.http.proxyHost=localhost
systemProp.http.proxyPort=8123

```

One for http and one for https. Also you can do it without creating a gradle.properties file, but also with cli
Like this

`gradlew -Dhttp.proxyHost=localhost -Dhttp.proxyPort=8123 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8123`

I think this one should be easier to implement for you as you don't need to creat a new file. So you can add it to dryrun cli for example like this too:
`dryrun -Dhttp.proxyHost=localhost -Dhttp.proxyPort=8123 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8123`

Hope these would help ;)
