### ISSUE TITLE
How can I use it on windows?

### ISSUE THREAD

**Issue by liangWenPeng** [cesarferreira/dryrun#26]

**Comment by cesarferreira** [comment]
Just install ruby for windows http://rubyinstaller.org/
and then `gem install dryrun`

**Comment by FantasyCheese** [comment]
I've install ruby for windows but encounter permission denied problem like #12 , is there any fix for it?

**Comment by AhmedvHashem** [comment]
same here

**Comment by luispereira** [comment]
hi @AhmedHashemNTS can you provide the logs so I can take a look?
This was fixed a long time ago, as the temporary folder on windows required permissions to run from there.

**Comment by AhmedvHashem** [comment]
gem install dryrun
gives me this 

<strong>ERROR:  Loading command: install (ArgumentError)
        unknown encoding name - CP720
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass</strong>

my gem version is 2.5.2 and ANDROID_HOME is set

**Comment by luispereira** [comment]
Hi, unknown encoding is related with character encoding, maybe you are suffering from this type of issue?
http://stackoverflow.com/a/22861206

**Comment by AhmedvHashem** [comment]
Thanks that fixed it

**Comment by homayoonahmadi** [comment]
If you got permission denied problem while installing RubyInstaller, just run it as administrator.

**Comment by knowamit** [comment]
```

C:\Ruby26-x64>gem install dryrun
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing dryrun:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ruby-ll-2.1.2/ext/
c
C:/Ruby26-x64/bin/ruby.exe -I C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0 -r ./siteco
nf20190221-9708-13lrri6.rb extconf.rb
creating Makefile

current directory: C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ruby-ll-2.1.2/ext/c
make "DESTDIR=" clean
current directory: C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ruby-ll-2.1.2/ext/c
make "DESTDIR="
make failedNo such file or directory - make "DESTDIR="

Gem files will remain installed in C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ruby-l
l-2.1.2 for inspection.
Results logged to C:/Ruby26-x64/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0
/ruby-ll-2.1.2/gem_make.out`

**Comment by qllwx** [comment]
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing nio4r:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nio4r-2.5.4/ext/nio4r
C:/Ruby27-x64/bin/ruby.exe -I C:/Ruby27-x64/lib/ruby/2.7.0 -r ./siteconf20201114-21136-j5a31d.rb extconf.rb

current directory: C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nio4r-2.5.4/ext/nio4r
make "DESTDIR=" clean
current directory: C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nio4r-2.5.4/ext/nio4r
make "DESTDIR="
make failedNo such file or directory - make "DESTDIR="

Gem files will remain installed in C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nio4r-2.5.4 for inspection.
Results logged to C:/Ruby27-x64/lib/ruby/gems/2.7.0/extensions/x64-mingw32/2.7.0/nio4r-2.5.4/gem_make.out
