### ISSUE TITLE
Manifest is in a different location than the code specifies

### ISSUE THREAD

**Issue by dvoiss** [cesarferreira/dryrun#28]
The code currently searches for the manifest file here:

``` ruby
path_to_manifest = File.join(path_to_sample, 'src/main/AndroidManifest.xml')
```

Some projects don't have the manifest file in this location. For instance dryrun will fail with the repo [Flex Layout](https://github.com/mmin18/FlexLayout) due to it's manifest being at `path_to_sample/AndroidManifest.xml`.

**Comment by cesarferreira** [comment]
`dryrun 0.6.4` includes all of your code submissions,
Thanks for making this tool greater 👍
