### ISSUE TITLE
Gradle Build Fail

### ISSUE THREAD

**Issue by esafirm** [cesarferreira/dryrun#3]
Hi, i always get this message when i tried to run it

``` bash
** cloning process **

Failure [DELETE_FAILED_INTERNAL_ERROR]
gradlew: 158: gradlew: Syntax error: "(" unexpected

Installing github.cesarferreira.helloworld...
executing: adb shell am start -n "github.cesarferreira.helloworld/github.cesarferreira.helloworld.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER

Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=github.cesarferreira.helloworld/.MainActivity }
Error type 3
Error: Activity class {github.cesarferreira.helloworld/github.cesarferreira.helloworld.MainActivity} does not exist.
```

any idea? Thanks and BTW, i love your idea.

**Comment by cesarferreira** [comment]
Thanks man :+1: 

That's weird, I guess it's not related to `dryrun`, 

gradlew:159 has this:

```
# Split up the JVM_OPTS And GRADLE_OPTS values into an array, following the shell quoting and substitution rules
function splitJvmOpts() {
    JVM_OPTS=("$@") 
}
```

Please go to the project's folder in the terminal and type:

> ./gradlew clean assemble installDebug

And tell me what the output is

**Comment by esafirm** [comment]
/gradlew clean assemble installDebug

The whole process run successfully, but it does download the gradle first, is it affecting the process?

``` bash
** building process **

Installing APK 'app-debug.apk' on 'Nexus7 - 5.1'
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 14.263 secs
```

**Comment by cesarferreira** [comment]
Now that that gradle version is downloaded, does dryrun run successfully?
If not can you paste all the output?

**Comment by esafirm** [comment]
Nope. I'm using Ubuntu 14.04 by the way

``` bash
dryrun https://github.com/cesarferreira/android-helloworld

/usr/lib/ruby/gems/1.9.1/gems/dryrun-0.4.1/lib/dryrun.rb:12: warning: Insecure world writable dir /opt/mongodb/bin in PATH, mode 040777
Cloning into '/tmp/dryrun/cesarferreira/android-helloworld'...
remote: Counting objects: 124, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 124 (delta 35), reused 124 (delta 35), pack-reused 0
Receiving objects: 100% (124/124), 2.24 MiB | 873.00 KiB/s, done.
Resolving deltas: 100% (35/35), done.
Checking connectivity... done.
Success
gradlew: 158: gradlew: Syntax error: "(" unexpected
Installing github.cesarferreira.helloworld...
executing: adb shell am start -n "github.cesarferreira.helloworld/github.cesarferreira.helloworld.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER

Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=github.cesarferreira.helloworld/.MainActivity }
Error type 3
Error: Activity class {github.cesarferreira.helloworld/github.cesarferreira.helloworld.MainActivity} does not exist.

> If you want to remove the app you just installed, execute:
adb uninstall github.cesarferreira.helloworld

```

**Comment by cesarferreira** [comment]
What's your jdk and java versions?
@esafirm please do a:

> gem install dryrun

I can see that you're using 1.9.1

> /usr/lib/ruby/gems/1.9.1/gems/

which is not supported by a few of my gems, you need at least 2.0.0.
after installing >2.2.0 (I recommend `rvm`) let me know if the problems persists and I'll re-open the issue

**Comment by akashk92** [comment]
gradlew: 158: gradlew: Syntax error: "(" unexpected
adb server is out of date.  killing...
cannot bind 'tcp:5037'
ADB server didn't ACK
- failed to start daemon *
  error: 
  Installing com.dk.sample.folder.residemenu...
  executing: adb shell am start -n "com.dk.sample.folder.residemenu/com.dk.sample.folder.residemenuMenuActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER

adb server is out of date.  killing...
- daemon started successfully *
  error: device not found

> If you want to remove the app you just installed, execute:
> adb uninstall com.dk.sample.folder.residemenu

**Comment by cesarferreira** [comment]
@akashk92 can you please tell me:
- ruby version
- github url (is this one? https://github.com/dkmeteor/Folder-ResideMenu)

**Comment by akashk92** [comment]
ruby gem version : 2.4.7
yes I am trying to fetch same url

**Comment by cesarferreira** [comment]
Works fine on my end mate, have you tried to kill your adb, disconnect and connect the device?
I can read **error: device not found**
which causes the gradle's build to fail

**Comment by akashk92** [comment]
I am trying with genymotion
and Yes i tried killing and restarting it..

**Comment by akashk92** [comment]
I have also set path Envirmnt and sdk path in genymotion settings

**Comment by cesarferreira** [comment]
What if you close genymotion and run a real device, does it work?

**Comment by akashk92** [comment]
kind of a different problem with emulator (This tym I tried another libary):

Cloning into '/tmp/dryrun/sacot41/SCViewPager'...
remote: Counting objects: 189, done.
remote: Total 189 (delta 0), reused 0 (delta 0), pack-reused 189
Receiving objects: 100% (189/189), 2.89 MiB | 567.00 KiB/s, done.
Resolving deltas: 100% (50/50), done.
Checking connectivity... done.
gradlew: 158: gradlew: Syntax error: "(" unexpected
Failed
Installing com.dev.sacot41.myresume...
executing: adb shell am start -n "com.dev.sacot41.myresume/com.dev.sacot41.myresume.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER

Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.dev.sacot41.myresume/.MainActivity }
Error type 3
Error: Activity class {com.dev.sacot41.myresume/com.dev.sacot41.myresume.MainActivity} does not exist.

> If you want to remove the app you just installed, execute:
> adb uninstall com.dev.sacot41.myresume

**Comment by cesarferreira** [comment]
Looks like it has something to do with your linux way to handle bash scripts
http://unix.stackexchange.com/questions/45781/shell-script-fails-syntax-error-unexpected

**Comment by akashk92** [comment]
Sorry I am not able to understand the issue and your given hint/solution

**Comment by cesarferreira** [comment]
It's something on your end, google your error ;) sorry I can't help mate, good luck!

**Comment by cesarferreira** [comment]
@akashk92 wanna take a look at #14 ? it looks like the issue was happening because of a missing android API

**Comment by rpattabi** [comment]
This issue needs to be reopened. I am on Ubuntu 14.04.

```
 [~] $ ruby -v
ruby 2.2.5p241 (2016-02-24 revision 53909) [x86_64-linux]

~
 [~] $ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

~
 [~] $ dryrun https://github.com/hnrainll/learn-android -p RadioButtoDemo
Cloning into '/tmp/dryrun/hnrainll/learn-android'...
remote: Counting objects: 1546, done.
remote: Total 1546 (delta 0), reused 0 (delta 0), pack-reused 1546
Receiving objects: 100% (1546/1546), 5.88 MiB | 1.38 MiB/s, done.
Resolving deltas: 100% (569/569), done.
Checking connectivity... done.
Using custom app folder: RadioButtoDemo
gradlew: 158: gradlew: Syntax error: "(" unexpected
Failed
Installing com.leochin.radiobuttodemo...
executing: adb shell am start -n "com.leochin.radiobuttodemo/com.leochin.radiobuttodemo.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER

Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.leochin.radiobuttodemo/.MainActivity }
Error type 3
Error: Activity class {com.leochin.radiobuttodemo/com.leochin.radiobuttodemo.MainActivity} does not exist.

> If you want to remove the app you just installed, execute:
adb uninstall com.leochin.radiobuttodemo

~
 [~] $ 
```

**Comment by cesarferreira** [comment]
@rpattabi which version of dryrun are you running? the last one is `0.5.6`

**Comment by rpattabi** [comment]
I have 0.5.1. I will try with the latest when I get a chance and update here. Thanks.

**Comment by cesarferreira** [comment]
did it fix it @rpattabi ?

**Comment by rpattabi** [comment]
Yes, it works fine! Thanks.
I checked it on this config:

```
~
 [~] $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty

 [~] $ ruby -v
ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-linux]

~
 [~] $ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

~
 [~] $ dryrun -v
0.6.4

```

**Comment by cesarferreira** [comment]
Great 🎉 thanks for the feedback
