### ISSUE TITLE
SSL_connect issue

### ISSUE THREAD

**Issue by hibob224** [cesarferreira/dryrun#34]
Currently getting SSL errors using any commands on versions 0.7.0 and 0.7.1 running on a Windows 10 machine. Version 0.6.5 works fine.

> C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
>         from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in`connect'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:852:in`start'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:319:in `open_http'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:737:in`buffer_open'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:210:in`catch'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:151:in`open_uri'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:717:in `open'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:35:in`open'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.1/lib/dryrun/dryrun_utils.rb:22:in `get_latest_version'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.1/lib/dryrun/dryrun_utils.rb:30:in`is_up_to_date'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.1/lib/dryrun.rb:71:in `outdated_verification'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.1/lib/dryrun.rb:14:in`initialize'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.1/bin/dryrun:5:in `new'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.1/bin/dryrun:5:in`<top (required)>'
>         from C:/Ruby23-x64/bin/dryrun:23:in `load'
>         from C:/Ruby23-x64/bin/dryrun:23:in`<main>'

**Comment by luispereira** [comment]
Same happened to be when I was on my work network. I had to follow these steps in order to fix it, probably can help you as well.
http://stackoverflow.com/a/16134586/706833
https://gist.github.com/luislavena/f064211759ee0f806c88

I might have a fix for this without doing the steps above, although I can only test this later today.

**Comment by cesarferreira** [comment]
I can't test it as I don't own a windows machine, thanks @luispereira for helping!

**Comment by cesarferreira** [comment]
Thanks @luispereira !
@hibob224 let me know if it works for you

**Comment by hibob224** [comment]
0.7.3 gives a new SSL error

> C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.3/lib/dryrun/dryrun_utils.rb:23:in `get_latest_version': uninitialized constant DryRun::DryrunUtils::OpenSSL (NameError)
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.3/lib/dryrun/dryrun_utils.rb:37:in`is_up_to_date'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.3/lib/dryrun.rb:71:in `outdated_verification'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.3/lib/dryrun.rb:14:in`initialize'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.3/bin/dryrun:5:in `new'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.3/bin/dryrun:5:in`<top (required)>'
>         from C:/Ruby23-x64/bin/dryrun:23:in `load'
>         from C:/Ruby23-x64/bin/dryrun:23:in`<main>'

**Comment by luispereira** [comment]
Hi, @hibob224 which version of ruby do you have?

**Comment by hibob224** [comment]
ruby 2.3.0p0 (2015-12-25 revision 53290) [x64-mingw32]

**Comment by luispereira** [comment]
You are right in other PC I got the same error. I believe that in some systems is required to explicit call the OpenSSL dependency. I will fix this asap. Sorry for the trouble.

**Comment by cesarferreira** [comment]
@hibob224 can you check the new version to see if it fixes your issue

**Comment by hibob224** [comment]
Works great, thanks guys :+1:

**Comment by yinhaojun** [comment]
@hibob224  how did you fix this issue.  I got the same issue.

**Comment by cesarferreira** [comment]
You replied in issue #71
