### ISSUE TITLE
Ubuntu 16.04 installation woes

### ISSUE THREAD

**Issue by ragunathjawahar** [cesarferreira/dryrun#35]
I don't have much experience with Ruby, any pointers would be helpful. I can see how `dryrun` can be extremely helpful, I just need to get it up and running. Thank you for your wonderful contribution. I have already installed `alfi`, `international` and `lasertag`.

I'm trying to install `dryrun` on my Ubuntu PC but I couldn't.

When I do a `sudo gem install dryrun`

I get this,

```
Building native extensions.  This could take a while...
ERROR:  Error installing dryrun:
    ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/rjb-1.5.4/ext
/usr/bin/ruby2.3 -r ./siteconf20160523-23370-6ujxs4.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
extconf.rb:53:in `<main>': JAVA_HOME is not set. (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/rjb-1.5.4 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rjb-1.5.4/gem_make.out
```

I took a look at the logged results and then I found the following information,

```
current directory: /var/lib/gems/2.3.0/gems/rjb-1.5.4/ext
/usr/bin/ruby2.3 -r ./siteconf20160523-23370-6ujxs4.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
extconf.rb:53:in `<main>': JAVA_HOME is not set. (RuntimeError)

extconf failed, exit code 1
```

The error says `JAVA_HOME` is not set, but when I echo the path, it works.

`echo $JAVA_HOME` returns `/usr/lib/jvm/java-8-oracle`

My `ruby` version is `ruby 2.3.0p0 (2015-12-25) [x86_64-linux-gnu]`

Let me know if you need more information. Thanks again.

**Comment by cesarferreira** [comment]
Hey man! Thanks a lot for your compliments 👍 
Glad to hear that my libs are being useful.

---

Are you sure that that's really your home path? look at mine:

``` bash
$ echo $JAVA_HOME                                                                                                                                        
/Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home
```

Take a look at this: https://github.com/arton/rjb/issues/40

**Comment by ragunathjawahar** [comment]
@cesarferreira I managed to install `rjb` on Ubuntu by following this [answer](http://stackoverflow.com/a/13721174/421372) on SO. Should we keep this open until the `rjb` issue is resolved? Someone could find it useful.

**Comment by cesarferreira** [comment]
I agree with you @ragunathjawahar, thanks 👍

**Comment by lionmoon60** [comment]
This is a good answer that works for me [stackoverflow](https://stackoverflow.com/questions/19439536/not-able-to-install-stanford-core-nlp-gem)
**The answer is** 
In the console just type these (remember to change to your current location)

export ANDROID_HOME=$HOME/Android/Sdk

**Comment by FoushWare** [comment]
I have faced the same issue and this answer fix it for me 
[stackoverflow](https://stackoverflow.com/questions/19439536/not-able-to-install-stanford-core-nlp-gem)
**The answer is** 
This is because JAVA_HOME is getting reset in the sudo mode. To fix it, open your /etc/sudoers file add the following line and save it.

Defaults   env_keep += "JAVA_HOME"
now reopen the terminal and install the gem
