### ISSUE TITLE
Unable to work with custom Gradle project structure

### ISSUE THREAD

**Issue by ragunathjawahar** [cesarferreira/dryrun#36]
Hi @cesarferreira, once again thank you for all your hard work for making our lives easier :)

Can we make `dryrun` work with custom Gradle projects too? Currently, the Android project the tool makes use of the Android project directory structure for detection. This makes it impossible to run projects with a different project structure like Jake Wharton's [u2020](https://github.com/jakewharton/u2020).

Do you have ideas to make it more generic? For instance, use a Gradle AST library to parse the `build.gradle` file and check for the application of Android plugin. Wouldn't this be more failsafe? Thanks again.

**Comment by luispereira** [comment]
Hi @ragunathjawahar, 
I believe that U2020 uses git commands and throws runtime exception if the project does not have a .git folder. Therefore I believe you could not run the U2020 through `gradlew assembleRelease`without changing the build.gradle.

One thing that dryrun can do is when there is no settings.gradle assume that the project has only a module (the app module). However nowadays I believe projects without settings.gradle are less than 1%.

**Comment by cesarferreira** [comment]
Hey man, thanks again for your kind words.
Currently I search for a `settings.gradle` file, I'll remove that check as @luispereira pointed out.
