### ISSUE TITLE
AdbSdkLib::AdbError

### ISSUE THREAD

**Issue by sergueioutenkov** [cesarferreira/dryrun#38]
Hey man, first of all thanks for this awesome library, i use in on my mac. 
But trying to make it work on my linux machine i get the following:

`Searching for devices...
/home/serguei/.rvm/gems/ruby-2.3.0/gems/adb-sdklib-0.0.3/lib/adb-sdklib.rb:106:in block in load_sdk_tools_jar: Not found /Users/serguei/Library/Android/sdk/tools/lib/ddmlib.jar (AdbSdkLib::AdbError)
    from /home/serguei/.rvm/gems/ruby-2.3.0/gems/adb-sdklib-0.0.3/lib/adb-sdklib.rb:104:in each
    from /home/serguei/.rvm/gems/ruby-2.3.0/gems/adb-sdklib-0.0.3/lib/adb-sdklib.rb:104:in load_sdk_tools_jar
    from /home/serguei/.rvm/gems/ruby-2.3.0/gems/adb-sdklib-0.0.3/lib/adb-sdklib.rb:54:in initialize
    from /home/serguei/.rvm/gems/ruby-2.3.0/gems/dryrun-0.7.6/lib/dryrun.rb:101:in new
    from /home/serguei/.rvm/gems/ruby-2.3.0/gems/dryrun-0.7.6/lib/dryrun.rb:101:in pick_device
    from /home/serguei/.rvm/gems/ruby-2.3.0/gems/dryrun-0.7.6/lib/dryrun.rb:149:in call
    from /home/serguei/.rvm/gems/ruby-2.3.0/gems/dryrun-0.7.6/bin/dryrun:5:in <top (required)>
    from /home/serguei/.rvm/gems/ruby-2.3.0/bin/dryrun:23:in load
    from /home/serguei/.rvm/gems/ruby-2.3.0/bin/dryrun:23:in <main>
    from /home/serguei/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in eval
    from /home/serguei/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in <main>`

Any thoughts?
Thanks in advance

**Comment by cesarferreira** [comment]
Hey man,
thanks for the compliment.

Can you show me the output of this command:

```
echo $ANDROID_HOME
```

mine outputs this:

> /Users/cesarferreira/Library/Android/sdk

**Comment by sergueioutenkov** [comment]
Mine this:

`/Users/serguei/Library/Android/sdk`

**Comment by cesarferreira** [comment]
what about this one

>  echo $JAVA_HOME

**Comment by sergueioutenkov** [comment]
JAVA_HOME:

> /usr/lib/jvm/java-1.7.0-openjdk-amd64

RUBY VERSION:

> ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

DRYRUN VERSION:

> 0.7.6

---

Sorry, should've given you this data in the first place.

**Comment by cesarferreira** [comment]
No problem,
look at my java home:

> /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home

**Comment by sergueioutenkov** [comment]
Sorry, but i don't get your point

**Comment by cesarferreira** [comment]
your java home is at the root of your jvm and my java home is at the **/Contents/Home** of my jvm, get it?

**Comment by sergueioutenkov** [comment]
But you're on OSx

**Comment by cesarferreira** [comment]
I haven't used linux in some time but I believe it's the same folder structure

**Comment by sergueioutenkov** [comment]
I believe in OSx the path to the "/bin" folder is the one you have, inside "Contents/Home" (I have the same on my Macbook), but in linux "/bin" is in the root of the JDK folder. 

Plus i never had other issues, and `javac -version` and `java -version` output the version correctly :(

**Comment by cesarferreira** [comment]
I have no idea what's going on then, do you know ruby?

**Comment by sergueioutenkov** [comment]
Me neither, and no i'm not familiar with ruby. I'll investigate this though and if i find something i'll let you know. Thanks!

**Comment by luispereira** [comment]
Hi @sergueioutenkov 
Did you tried `sudo apt-get install openjdk-7-jdk`  once again?

There was a problem for me once, where I had multiple configurations of java and I had to execute this command to map it properlly.

**Comment by sergueioutenkov** [comment]
Hey @luispereira, thanks for the tip.
I just tried what you said, but no visible change, still the same error :cry:

**Comment by meness** [comment]
I have the same problem on Windows 10.

> C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/adb-sdklib-0.0.3/lib/adb_sdklib/common.rb:69:in `import': Constants DL and Fiddle is not defined. (RuntimeError)
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/adb-sdklib-0.0.3/lib/adb_sdklib/common.rb:69:in`module:Common'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/adb-sdklib-0.0.3/lib/adb_sdklib/common.rb:67:in `<module:AdbSdkLib>'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/adb-sdklib-0.0.3/lib/adb_sdklib/common.rb:4:in`<top (required)>'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/adb-sdklib-0.0.3/lib/adb-sdklib.rb:3:in `<top (required)>'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.7/lib/dryrun.rb:1:in`<top (required)>'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>         from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
>         from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.7.7/bin/dryrun:3:in `<top (required)>'
>         from C:/Ruby23-x64/bin/dryrun:23:in`load'
>         from C:/Ruby23-x64/bin/dryrun:23:in `<main>'

**Comment by Savrov** [comment]
have the same problem as TC
$JAVA_HOME
`/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
$ANDROID_HOME
`/Users/cesarferreira/Library/Android/sdk/`

**Comment by luispereira** [comment]
AdbSdkLib was only added to fix the compatibility with windows OS, however I think I found other solution, and as soon as I can I will remove the lib, and hopefully all issues related.

**Comment by cesarferreira** [comment]
That would be amazing @luispereira ! :)

**Comment by SriKrishnaCovalense** [comment]
Seen the same problem as reported by @meNESS on Windows 8.1

> dryrun https://github.com/Yalantis/uCrop
> Error Log:
> C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/adb-sdklib-0.0.3/lib/adb_sdklib/common.rb:69:in `import': Constants DL and Fiddle is not defined. (RuntimeError)
>         from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/adb-sdklib-0.0.3/lib/adb_sdklib/common.rb:69:in`module:Common'
>         from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/adb-sdklib-0.0.3/lib/adb_sdklib/common.rb:67:in `<module:AdbSdkLib>'
>         from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/adb-sdklib-0.0.3/lib/adb_sdklib/common.rb:4:in`<top (required)>'
>         from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
>         from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
>         from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/adb-sdklib-0.0.3/lib/adb-sdklib.rb:3:in `<top (required)>'
>         from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
>         from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
>         from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/dryrun-0.7.7/lib/dryrun.rb:1:in`<top (required)>'
>         from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
>         from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
>         from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/dryrun-0.7.7/bin/dryrun:3:in `<top (required)>'
>         from C:/RailsInstaller/Ruby2.2.0/bin/dryrun:23:in`load'
>         from C:/RailsInstaller/Ruby2.2.0/bin/dryrun:23:in `<main>'

**Comment by cesarferreira** [comment]
Hopefully the fix shipped on version `0.7.9` by @luispereira exterminates this bug, let me know if anything goes wrong guys 👍
