### ISSUE TITLE
need download gradle everytime?

### ISSUE THREAD

**Issue by lvandroid** [cesarferreira/dryrun#39]
when I run dryrun command，download gradle everytime, how to resolve the problem?

**Comment by cesarferreira** [comment]
Gradle will download a version if you don't have it yet on your computer.
If you go here:

> ls ~/.gradle/wrapper/dists

you'll see all the versions you already downloaded

Cheers mate

**Comment by jamie1052741705** [comment]
但是那样还是需要下载好多gradle版本，能不能设置本地已经有的gradle版本

**Comment by lvandroid** [comment]
这个决定于你要编译项目里build.gradle脚本写的版本吧，应该不能

2016年12月19日 15:24，jamie1052741705 <notifications@github.com>写道：

但是那样还是需要下载好多gradle版本，能不能设置本地已经有的gradle版本

**Comment by cesarferreira** [comment]
Hey,
Please write in english, I won't be able to help otherwise

**Comment by lvandroid** [comment]
he thinks it's unfriendly too many gradle files to download, and want to set a specified version.  but I think it depends on the project you want to build, can't do that


2016年12月20日 08:09，César Ferreira <notifications@github.com>写道：

Hey,
Please write in english, I won't be able to help otherwise

**Comment by cesarferreira** [comment]
You're totally right, it's project dependant, thanks for translating
