### ISSUE TITLE
No Java runtime present, requesting install

### ISSUE THREAD

**Issue by saket** [cesarferreira/dryrun#41]
Hello, I'm seeing this error when trying to use dryrun. It opens a dialog suggesting me to install the "legacy Java SE 6 runtime". Does this mean I cannot use it with Java 8?

**Comment by cesarferreira** [comment]
Hey,
I only have `java8` installed.

Can you tell me more details?
Your OS,
your $JAVA_HOME
your $ANDROID_HOME
ruby version etc

**Comment by saket** [comment]
Looks like $JAVA_HOME and $ANDROID_HOME env variables aren't set on my system. Ruby version is `2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`.

Is the absence of JAVA_HOME and ANDROID_HOME variables the culprit here?

**Comment by cesarferreira** [comment]
That's probably it, here's mine:

echo $JAVA_HOME

> /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home

echo $ANDROID_HOME

> /Users/cesar/Library/Android/sdk/

**Comment by saket** [comment]
Nope, still doesn't work :( Still seeing the same error:

> No Java runtime present, requesting install.

<img width="398" alt="screen shot 2016-08-06 at 11 31 46 pm" src="https://cloud.githubusercontent.com/assets/2387680/17458440/f58ef35c-5c2d-11e6-858c-646ebe6603ca.png">

**Comment by cesarferreira** [comment]
I'm just googling your issue: http://anas.pk/2015/09/02/solution-no-java-runtime-present-mac-yosemite/

Which OS do you have?

**Comment by saket** [comment]
So I went ahead and installed the suggested **legacy** Java runtime 6 anyway and it worked. :D

However, unlike the tutorials (including the one you shared), running `java -version` in my terminal was printing the installed java version (1.9.0_92 Java(TM) SE Runtime Environment) fine, which suggests that a Java environment was indeed already present. I am hoping the two Java version installations will not result in any conflicts.

**Comment by cesarferreira** [comment]
I think it will use the one in `$JAVA_HOME` 👍 no biggie

**Comment by Isanderthul** [comment]
I set both my $JAVA_HOME and $ANDROID_HOME to be correct, I have ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]. The problem still occurs.
edit- 

I have OSX System Version:  OS X 10.11.5 (15F34)
and my java symlink: /usr/bin/java -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

edit-
➜  ~ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/
➜  ~ echo $ANDROID_HOME
/Users/x/Library/Android/sdk/
