### ISSUE TITLE
Shallow clone

### ISSUE THREAD

**Issue by PavelSynek** [cesarferreira/dryrun#42]
Is it possible to perform just a shallow clone? Some repos are very big and it's unnecessary to get the whole history.

**Comment by cesarferreira** [comment]
This is actually a great idea! I'll look into it and release an update asap :)

(Do you have a good big android sample repository URL for me to try and compare times?)

**Comment by cesarferreira** [comment]
Shallow clones are now being used 👍 thanks for the tip
