### ISSUE TITLE
your $ANDROID_HOME is not defined

### ISSUE THREAD

**Issue by w0080626** [cesarferreira/dryrun#50]
WARNING: your $ANDROID_HOME is not defined

hint: in your ~/.bashrc or ~/.bash_profile  add:
  export ANDROID_HOME="/Users/cesarferreira/Library/Android/sdk/"

Now type source ~/.bashrc

But, I have set up ANDROID_HOME and JAVA_HOME

Why have this problem? 

I look forward to your reply

**Comment by cesarferreira** [comment]
Maybe you're not using bash?

```
echo $SHELL
```

What does it output?

**Comment by w0080626** [comment]
Thank you for your reply, there is no problem now.

**Comment by sven-xie** [comment]
How do you solve this problem? I look forward to your reply,thank you !

**Comment by cesarferreira** [comment]
You can just google it: https://www.google.co.uk/search?q=how+to+set+%24ANDROID_HOME+is+not+defined&oq=how+to+set+%24ANDROID_HOME+is+not+defined&aqs=chrome..69i57.1311j0j1&sourceid=chrome&ie=UTF-8#safe=off&q=+%24ANDROID_HOME+is+not+defined
