### ISSUE TITLE
How to use in window?

### ISSUE THREAD

**Issue by flyjin** [cesarferreira/dryrun#51]
怎么在window系统上使用? 小白提问

**Comment by cesarferreira** [comment]
I'm sorry man, I'm not Chinese, yet, if you're asking how to use no windows, you just need to install ruby and run `gem install dryrun`

**Comment by flyjin** [comment]
I can not find the installation of the options, there is no exe installation files, and thank you for your answer

**Comment by cesarferreira** [comment]
it's right there https://github.com/cesarferreira/dryrun#installation
