### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by zhang-weifu** [cesarferreira/dryrun#52]
When i install with gem command: raise below error: who can tell me how to fixed it?

ERROR:  Error installing dryrun:
    ERROR: Failed to build gem native extension.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
```

creating Makefile

make "DESTDIR="
make: **\* No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin15/ruby/config.h', needed by`driver.o'.  Stop.

**Comment by cesarferreira** [comment]
have you run this on your terminal?

```
xcode-select --install
```

**Comment by zhang-weifu** [comment]
oh,after install xcode command tools, It work for me.
Sorry for this stupid question.
