### ISSUE TITLE
can,t find my device

### ISSUE THREAD

**Issue by yalker** [cesarferreira/dryrun#53]
windows , when i run dryrun url, tips "Searching for devices.." and no devices attached, however i can,t connect my devices,i am sure all the setting is right

**Comment by luispereira** [comment]
Hi, each dryrun version you are using?

**Comment by cesarferreira** [comment]
if you run `adb devices` what happens?

**Comment by krokyze** [comment]
I'm experiencing the same problem. However "adb devices" returns list with one device attached.

**Comment by cesarferreira** [comment]
can you show me the `dryrun` run log?

**Comment by krokyze** [comment]
At the moment can't reproduce. 

But it was something like:

```
Searching for devices...
no devices attached, but will still continue
```

**Comment by cesarferreira** [comment]
Are you completely sure that the phone was being listed in the `adb devices`? because I use this everyday and that never happened to me.

**Comment by krokyze** [comment]
Yes. Maybe it was somehow in conflict with Android Studio opened?
I was experiencing this only for the first times together with #54 
After I tried with other git repo and dryrun got till gradle build, then device showed up.

**Comment by cesarferreira** [comment]
Maybe `adb` was killed by android studio for some reason, some weird edge case.

Let me know if it happens again!

Thanks for reporting the issue
