### ISSUE TITLE
How to solve this bug？

### ISSUE THREAD

**Issue by 1242128273wangpeng** [cesarferreira/dryrun#64]
![qq 20161111095140](https://cloud.githubusercontent.com/assets/10842360/20201689/de653e62-a7f4-11e6-9a75-07a0b9579641.png)
![qq 20161111094702](https://cloud.githubusercontent.com/assets/10842360/20201717/0a003d38-a7f5-11e6-86cb-5b6acce84e29.png)

**Comment by cesarferreira** [comment]
Can you give me the command you ran?

```
dryrun ...??
```

**Comment by 1242128273wangpeng** [comment]
Yes, I run it just like this 
![qq 20161114090424](https://cloud.githubusercontent.com/assets/10842360/20250519/80db508a-aa4a-11e6-9ba2-0696b643bc75.png)

I try many projects,always remind me like this 
![qq 20161114090915](https://cloud.githubusercontent.com/assets/10842360/20250512/68f75a0e-aa4a-11e6-99a7-4a17de6970bc.png)
 Whether my android studio cause this exception or not?

**Comment by luispereira** [comment]
There are 2 strange behaviours, despite de exception being called. 
1 - Dryrun catching, multiple devices, despite being only one
2 - Outdate processing is not working in your case

which version of dryrun are you using?
(if you do not have the latest version of dryrun, run the command `gem install dryrun`)

However this is working on my side (windows 10) with dryrun 0.8.1

**Comment by cesarferreira** [comment]
I believe the non existing multiple devices were fixed in the latest build by @luispereira.
This doesn't look like an issue related to `dryrun`, your windows machine is not being able to compile the project, try to compile it manually and report in this thread if it didn't solve the issue
