### ISSUE TITLE
Couldn't open, sorry!

### ISSUE THREAD

**Issue by SteveEdson** [cesarferreira/dryrun#7]
I receive the error message when running `dryrun https://github.com/googlesamples/android-RuntimePermissions.git`.

Is there a verbose mode to help pinpoint the issue?

> Cloning into '/var/folders/9c/0qmt89ls7mv_1f_3bdmgrfy40000gn/T/dryrun/googlesamples/android-RuntimePermissions'...
> remote: Counting objects: 163, done.
> remote: Total 163 (delta 0), reused 0 (delta 0), pack-reused 163
> Receiving objects: 100% (163/163), 503.07 KiB | 886.00 KiB/s, done.
> Resolving deltas: 100% (41/41), done.
> Checking connectivity... done.
> Couldn't open, sorry!

**Comment by cesarferreira** [comment]
Hey mate! 
I was missing a slash in a folder's path, I found it and fixed it :)

thanks a lot for reporting it!

do a 

> gem install dryrun

the `0.4.3` should fix it 

let me know if it worked for you @SteveEdson

**Comment by SteveEdson** [comment]
Much better, thanks!

**Comment by cesarferreira** [comment]
Thanks for the help mate :) have a great one
