### ISSUE TITLE
can not find adb, please help me

### ISSUE THREAD

**Issue by yinhaojun** [cesarferreira/dryrun#70]
/usr/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory - /platform-tools/adb (Errno::ENOENT)
	from /usr/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
	from /usr/lib/ruby/2.3.0/open3.rb:95:in `popen3'
	from /var/lib/gems/2.3.0/gems/dryrun-0.8.1/lib/dryrun/dryrun_utils.rb:50:in `run'
	from /var/lib/gems/2.3.0/gems/dryrun-0.8.1/lib/dryrun/dryrun_utils.rb:46:in `run_adb'
	from /var/lib/gems/2.3.0/gems/dryrun-0.8.1/lib/dryrun.rb:108:in `pick_device'
	from /var/lib/gems/2.3.0/gems/dryrun-0.8.1/lib/dryrun.rb:171:in `call'
	from /var/lib/gems/2.3.0/gems/dryrun-0.8.1/bin/dryrun:5:in `<top (required)>'
	from /usr/local/bin/dryrun:23:in `load'
	from /usr/local/bin/dryrun:23:in `<main>'

qinqin@qinqin:~$ env | grep "ANDROID_HOME"
ANDROID_HOME=/home/qinqin/android/android-sdk-linux
qinqin@qinqin:~$ which adb
/home/qinqin/android/android-sdk-linux/platform-tools/adb

my os is ubuntu 16.04lts!
please help me. thanks

**Comment by cesarferreira** [comment]
Hi,
although this doesn't seem to be a `dryrun` issue, can you try to run `adb devices` ?

make sure you don't have multiple sdk's installed (happened to me once)

**Comment by cesarferreira** [comment]
according to #72 you already fixed this issue
