### ISSUE TITLE
help me， thank you   

### ISSUE THREAD

**Issue by yinhaojun** [cesarferreira/dryrun#72]
qinqin@qinqin:~$ dryrun git@github.com:llxdaxia/RecyclerView.git
Searching for devices...
Picked 1ae2d6d67d13
Found project in /tmp/dryrun/llxdaxia/RecyclerView...
HEAD 现在位于 ebea069 Update README.md
正在获取 origin
已经位于 'master'
您的分支与上游分支 'origin/master' 一致。
来自 github.com:llxdaxia/RecyclerView
 * branch            master     -> FETCH_HEAD
Already up-to-date.
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html.

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/dryrun/llxdaxia/RecyclerView/RefreshRecyclerView/build.gradle' line: 50

* What went wrong:
A problem occurred evaluating project ':RefreshRecyclerView'.
> Could not read script 'https://raw.githubusercontent.com/llxdaxia/GradleScript/master/install_v1.gradle'.
   > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.315 secs

======================================================

 Something went wrong while executing this:
  $ ./gradlew clean

======================================================

**Comment by cesarferreira** [comment]
I works fine on my side, it appears that you can't access this URL 'https://raw.githubusercontent.com/llxdaxia/GradleScript/master/install_v1.gradle'.

maybe because you are behind a firewall or something alike

**Comment by yinhaojun** [comment]
i can open the url!  thi is the content:

apply plugin: 'com.github.dcendents.android-maven'

group = publishedGroupId                               // Maven Group ID for the artifact

install {
    repositories.mavenInstaller {
        // This generates POM.xml with proper parameters
        pom {
            project {
                packaging 'aar'
                groupId publishedGroupId
                artifactId artifact

**Comment by luispereira** [comment]
I'm also having problems running that project, and i opened a issue regarding this
https://github.com/llxdaxia/RecyclerView/issues/3

**Comment by yinhaojun** [comment]
@luispereira maybe becauseof llxdaxia/RecyclerView project!   forgive my poor english, i am a chinese! :)

**Comment by yinhaojun** [comment]
hello! 
i have a question. when the gradle version is diffrent, we need dowload the gradle everytime?
Downloading https://services.gradle.org/distributions/gradle-2.14.1-all.zip
.............................................................

**Comment by cesarferreira** [comment]
no, it will be only be downloaded once, it's gonna be cached to your `~/.gradle/` folder

**Comment by yinhaojun** [comment]
@cesarferreira   i deleted this folder! it downloading now!
