### ISSUE TITLE
error install dryrun

### ISSUE THREAD

**Issue by Coder-DanielHan** [cesarferreira/dryrun#75]
![image](https://cloud.githubusercontent.com/assets/6194550/20654107/fae1c498-b550-11e6-9618-d2d036b90660.png)

**Comment by luispereira** [comment]
Hi you might want to check #34 
And check this link https://gist.github.com/luislavena/f064211759ee0f806c88

This is an issue regarding SSL connections using ruby on windows.

Closing for now, if you any other problem regarding this, I will reopen.

**Comment by Coder-DanielHan** [comment]
Already solve this.But It comes out another problem in windows system. #9  And this issue has only solution for Mac.
