### ISSUE TITLE
No such file or directory - /platform-tools/adb (Errno::ENOENT)

### ISSUE THREAD

**Issue by ftc300** [cesarferreira/dryrun#77]
Why do I have the following error every time
![image](https://cloud.githubusercontent.com/assets/12816061/20955357/95f36f30-bc7d-11e6-9043-f9597981b455.png)

but 
➜  ~ source ~/.bash_profile
➜  ~ echo @ANDROID_HOME
@ANDROID_HOME
➜  ~ echo $ANDROID_HOME
/Users/***/Library/Android/sdk
?

**Comment by cesarferreira** [comment]
What was the problem?

**Comment by SuperMasterBlasterLaser** [comment]
@cesarferreira I have also encountered this problem:

C:\>dryrun -c
Searching for devices...
D:/Ruby23-x64/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory
- D:\path\to\my\sdk/platform-tools/adb.exe  devices  (Errno::ENOENT)
        from D:/Ruby23-x64/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
        from D:/Ruby23-x64/lib/ruby/2.3.0/open3.rb:95:in `popen3'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.9.0/lib/dryrun/dryr
un_utils.rb:54:in `run'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.9.0/lib/dryrun/dryr
un_utils.rb:46:in `run_adb'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.9.0/lib/dryrun.rb:1
08:in `pick_device'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.9.0/lib/dryrun.rb:1
68:in `call'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/dryrun-0.9.0/bin/dryrun:6:in
 `<top (required)>'
        from D:/Ruby23-x64/bin/dryrun:22:in `load'
        from D:/Ruby23-x64/bin/dryrun:22:in `<main>'

However, I have ANDROID_HOME set in my environment variables and when I type adb, I can see it's commands.

**Comment by cesarferreira** [comment]
Can you create a separate issue @SuperMasterBlasterLaser please?

**Comment by thushcapone** [comment]
@ftc300 I have the same problem, what is the cause and what is the solution?

**Comment by luispereira** [comment]
What is you ANDROID_HOME path @thushcapone ?

**Comment by thushcapone** [comment]
@luispereira I forgot to set it. The issue was related to it missing. Thank you
