### ISSUE TITLE
Couldn't open the sample project, sorry!

### ISSUE THREAD

**Issue by W-quan** [cesarferreira/dryrun#78]
dryrun https://github.com/pires/android-obd-reader
Searching for devices...
Picked 9b065547
正克隆到 '/var/folders/4d/64fng_x90yqbw5xywx9q7jzr0000gn/T/dryrun/pires/android-obd-reader'...
remote: Counting objects: 103, done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 103 (delta 6), reused 58 (delta 0), pack-reused 0
接收对象中: 100% (103/103), 390.32 KiB | 5.00 KiB/s, 完成.
处理 delta 中: 100% (6/6), 完成.
Couldn't open the sample project, sorry!

**Comment by cesarferreira** [comment]
https://github.com/pires/android-obd-reader

If you check the code, it has no sample project, that's why it can't be opened
