### ISSUE TITLE
Install dryrun failed

### ISSUE THREAD

**Issue by lct8712** [cesarferreira/dryrun#8]
Hi

I failed to install dryrun using gem, this is the error message:

➜  ~  gem install dryrun
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/quick/Marshal.4.8/dryrun-0.4.3.gemspec.rz)

How can I fix this?
Thanks

**Comment by cesarferreira** [comment]
Probably your firewall is blocking it. Not dryrun related. 
Let me know if it was it

**Comment by lct8712** [comment]
It is the firewall. The origin gem source is blocked by China GFW, even though I am using a VPN.

The install succeed after I changed source of gem:

```
gem sources --remove https://rubygems.org/
gem sources -a https://ruby.taobao.org/
```

**Comment by cesarferreira** [comment]
Glad to hear that :+1:
