### ISSUE TITLE
why dose it always remind me outdated anytime I use it ?

### ISSUE THREAD

**Issue by snowjade** [cesarferreira/dryrun#80]
why dose it always remind me outdated anytime I use it ?
I don not know weather it is a bug ?
![image](https://cloud.githubusercontent.com/assets/11959369/21249891/39fc5510-c37c-11e6-8d07-6f4614be8bb7.png)

**Comment by luispereira** [comment]
I believe that this was an issue on 0.8.0 and 0.7.x versions, and it is now fixed 
@cesarferreira right?

**Comment by cesarferreira** [comment]
It's super weird that the `gem update dryrun` doesn't install the actual latest which is `0.9.0`

**Comment by snowjade** [comment]
problem is  solved now ,it is not the bug of dryrun . I just remove the sources https://gems.ruby-china.org/  and use the original source ,then dryrun can be updated to 0.9.0 .
