### ISSUE TITLE
ERROR:  Error installing dryrun:

### ISSUE THREAD

**Issue by vasskob** [cesarferreira/dryrun#81]
ERROR:  Error installing dryrun:
ERROR: Failed to build gem native extension.

Please add this to install tag for installing ruby-gem ( on ubuntu)

sudo apt-get install build-essential patch
sudo apt-get install ruby-dev zlib1g-dev liblzma-dev

**Comment by cesarferreira** [comment]
Hey, 
this looks like a faulty ruby installation, not a `dryrun` issue,

**Comment by verticalakash** [comment]
@vasskob i am facing the same issue.. have you solved it yet?

**Comment by vasskob** [comment]
Try this
sudo apt-get install build-essential patch
sudo apt-get install ruby-dev zlib1g-dev liblzma-dev
