### ISSUE TITLE
what is the gem?

### ISSUE THREAD

**Issue by guogailee** [cesarferreira/dryrun#82]
In Windows,if there is not the ruby environment,"the gem install dryrun"will not work.
How to resolve?Install ruby.

**Comment by RicardoBrazao** [comment]
While making coffee this morning, I didn't have any coffee. How to resolve? Buy coffee.

**Comment by luispereira** [comment]
@RicardoBrazao 
Priceless men. 

I will close this issue, I believe the solution is already there :)
