### ISSUE TITLE
No such file or directory - /platform-tools/adb (Errno::ENOENT)

### ISSUE THREAD

**Issue by binIoter** [cesarferreira/dryrun#84]
$ dryrun git@github.com:cesarferreira/android-helloworld.git
Searching for devices...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `spawn': No such file or directory - /platform-tools/adb (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-0.9.0/lib/dryrun/dryrun_utils.rb:54:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-0.9.0/lib/dryrun/dryrun_utils.rb:46:in `run_adb'
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-0.9.0/lib/dryrun.rb:108:in `pick_device'
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-0.9.0/lib/dryrun.rb:168:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-0.9.0/bin/dryrun:6:in `<top (required)>'
	from /usr/bin/dryrun:23:in `load'
	from /usr/bin/dryrun:23:in `<main>'

**Comment by luispereira** [comment]
Which version of dryrun you have? 
You can do this command on your console to know it `dryrun -v`
Also, where are your ANDROID_HOME environment point to?

**Comment by ragmha** [comment]
Steps to Fix this:

1. `echo export "ANDROID_HOME=/Users/yourName/Library/Android/sdk" >> ~/.bash_profile`

2. Close your terminal.

3. Reopen your terminal `echo $ANDROID_HOME` 

4. Test `dryrun git@github.com:cesarferreira/android-helloworld.git` 🎉

**Comment by cesarferreira** [comment]
Thanks @ragmha, although you don't need to close the terminal, just do `source ~/.bash_profile`

**Comment by hidetag** [comment]
I have the same problem recently.
Maybe after I installed oh-my-zsh.
Everytime I use "dryrun git..."，the same problem shows up.
So far，my solution is just do "source ~/.bash_profile". Then I can use dryrun one more time.after this，same problem.

"dryrun -v"  ---> 0.9.0
macOS Sierra 10.12.3

**Comment by cesarferreira** [comment]
if you installed oh-my-zsh you shouldn't use the `bash_profile` anymore, you should put the ANDROID_HOME etc in your `~/.zshrc`

**Comment by hidetag** [comment]
@cesarferreira Thx. Solved.

**Comment by Domonlee** [comment]
@cesarferreira Thx so much

**Comment by bpinela** [comment]
Android SDK requires 32-bit libraries. You probably are on 64-bit and need the 32-bit libs. Here are the troubleshooting directions from [developer.android.com](developer.android.com)

For Ubuntu 13.10 (Saucy Salamander) and above, install the libncurses5:i386, libstdc++6:i386, and zlib1g:i386 packages using apt-get:

sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libncurses5:i386 libstdc++6:i386 zlib1g:i386

For earlier versions of Ubuntu, install the ia32-libs package using apt-get:

apt-get install ia32-libs

**Comment by felquis** [comment]
For future wanderers, I saw this error because I was using relative paths in my export `~/Library/Android/sdk`, I changed it to use absolute paths and it worked fine `/Users/youruser/Library/Android/sdk`. Thank you. 👍
