### ISSUE TITLE
installDebug FAILED

### ISSUE THREAD

**Issue by snowjade** [cesarferreira/dryrun#86]
I do not think this is a problem of dryrun , I just write it  here  to try to find the solution .
this is the part console log . It seems  it can not install the apk automatic . maybe , dryrun
can just produce apk  as a option .

```
:sample:packageDebug
:sample:zipalignDebug
:sample:assembleDebug
:sample:installDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample:installDebug'.
> Failed to install on any devices.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 21.878 secs


======================================================

 Something went wrong while executing this:
  $ ./gradlew installDebug

======================================================


Xiang-mbp:~ Xiang$ adb devices
List of devices attached
192.168.31.150:5555	device
```

**Comment by cesarferreira** [comment]
What if you connect your device via USB instead of IP? Does it work?

**Comment by snowjade** [comment]
Sorry I did not respond promptly.
just for some of the app , it installDebug failed  whether via IP or USB.
but some of the others app ,it worked .
for example : https://github.com/afollestad/material-dialogs , it does not work .

**Comment by luispereira** [comment]
Actually, because I'm on windows I also can not use dryrun on that repository, because of a jack and jill bug
https://code.google.com/p/android/issues/detail?id=223700.
However, for me dryrun always picks the correctly device.

**Comment by cesarferreira** [comment]
Just tried it and it works on my side @snowjade

**Comment by snowjade** [comment]
yes, that is the condition . just some of the phone (eg mi  meizu zuk) from China can not work for some app by terminal command or dryrun , while only work with android studio . Maybe they have done something terrible to the original android system . @cesarferreira

**Comment by luispereira** [comment]
@snowjade are you sure you are using the same SDK directory that android studio is using? 
Remember new android studios have now a build in SDK and java environment. 
On windows this is very frustrating because I had to search this folder and change the environment variable path. 
Is that the case @snowjade ?

**Comment by snowjade** [comment]
![image](https://cloud.githubusercontent.com/assets/11959369/23011332/6235027e-f45b-11e6-9537-8414a01c2768.png)
![image](https://cloud.githubusercontent.com/assets/11959369/23011337/6d6b7c54-f45b-11e6-93ab-88c0829840fc.png)

you  see , I think I use the same sdk. (please ignore the red letter in the image). @luispereira

**Comment by cesarferreira** [comment]
why so specific? mine is just: `/Users/cesar/Library/Android/sdk`

**Comment by snowjade** [comment]
I install sdk by homebrew ,then, so specific.

**Comment by cesarferreira** [comment]
Yeah, that's ok then.

Just tried again and still works, by your logs it looks like it's not related to `dryrun`
