### ISSUE TITLE
dryrun install ok but -bash: dryrun: command not found

### ISSUE THREAD

**Issue by lyzqw** [cesarferreira/dryrun#87]
bogon:~ liuyuzhe$ sudo gem install -n /usr/local/bin dryrun
Password:
Successfully installed dryrun-0.9.0
Parsing documentation for dryrun-0.9.0
1 gem installed

**Comment by luispereira** [comment]
I believe this is not a dryrun issue. I think this is an issue regarding your ruby installation. 
Check if you have your binary ruby folder correctly set on environment path.

For example:
PATH=$PATH:/usr/lib/ruby/gems/1.8/bin

**Comment by cesarferreira** [comment]
Like @luispereira said, this is not a dryrun issue, you have a missing environment path 

btw: Why did you install outside your normal ruby path?
