### ISSUE TITLE
No online devices found

### ISSUE THREAD

**Issue by verticalakash** [cesarferreira/dryrun#88]
hi! i am facing this issue after this command

"dryrun https://github.com/cesarferreira/android-helloworld"

Skipping device '4d62caaf' (4d62caaf): Device is null.
:app:installDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No online devices found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 27.55 secs

======================================================

 Something went wrong while executing this:
  $ ./gradlew installDebug

======================================================

**Comment by cesarferreira** [comment]
run `adb devices`, what's the output?

**Comment by verticalakash** [comment]
$ adb devices
adb server is out of date.  killing...
* daemon started successfully *
List of devices attached 
????????????	no permissions

**Comment by cesarferreira** [comment]
Doesn't look like a `dryrun` issue, it's just your `adb` that is not finding your device

**Comment by verticalakash** [comment]
And after killing adb server i restart the adb server and then it showing

$ adb devices
List of devices attached 
4d62caaf	device

**Comment by cesarferreira** [comment]
Does dryrun work now?

**Comment by verticalakash** [comment]
unfortunately Not :(

**Comment by verticalakash** [comment]
well well well earlier i was using Android 6(OnePlus3) it didn't worked on it. and when i used Android 5(sony xperia) its working like butter. i don't understand why it is happening...
