### ISSUE TITLE
Git Clone issue

### ISSUE THREAD

**Issue by verticalakash** [cesarferreira/dryrun#89]
well when i am trying to clone this from this URL: https://github.com/airbnb/lottie-android

it gives me this error:
binary@binary:~$ dryrun  https://github.com/airbnb/lottie-androidSearching for devices...
Picked CB5A1QHGD5
fatal: Not a git repository (or any of the parent directories): .git
fatal: Could not get current working directory: No such file or directory

======================================================

 Something went wrong while executing this:
  $ git clone --depth 1 https://github.com/airbnb/lottie-android.git /tmp/dryrun/airbnb/lottie-android

======================================================

**Comment by cesarferreira** [comment]
`dryrun https://github.com/airbnb/lottie-androidSearching`

you pasted `SEARCHING` to the GIT url dude

**Comment by verticalakash** [comment]
No no.. i just copy past the error message from  my terminal.. i passed the correct url till "android"

**Comment by cesarferreira** [comment]
```
➜  ~ dryrun https://github.com/airbnb/lottie-android
Searching for devices...
No devices attached, but I'll run anyway
Cloning into '/var/folders/2c/mmsqykpd7pz9lpsxx_bpy8lm9kkl6z/T/dryrun/airbnb/lottie-android'...
remote: Counting objects: 355, done.
remote: Compressing objects: 100% (284/284), done.
remote: Total 355 (delta 72), reused 230 (delta 33), pack-reused 0
Receiving objects: 100% (355/355), 5.87 MiB | 1.30 MiB/s, done.
Resolving deltas: 100% (72/72), done.
```

works great here
