### ISSUE TITLE
Failed to build gem native extension.

### ISSUE THREAD

**Issue by WahdanZ** [cesarferreira/dryrun#9]
Building native extensions.  This could take a while...
ERROR:  Error installing dryrun:
    ERROR: Failed to build gem native extension.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
```

mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/nokogiri-1.6.6.2/ext/nokogiri/gem_make.out

**Comment by cesarferreira** [comment]
Not #dryun related but...

http://stackoverflow.com/questions/19580685/installing-rails-on-mavericks
The same issue, installing command line tools:

> xcode-select --install

shoud fix this.

**Comment by WahdanZ** [comment]
yes it fixed thanks

**Comment by Coder-DanielHan** [comment]
@cesarferreira how to solve it in windows system?
