### ISSUE TITLE
Building multi module projects

### ISSUE THREAD

**Issue by dEn13L** [cesarferreira/dryrun#90]
Are there plans for building multi module projects?

For example, https://github.com/stfalcon-studio/ChatKit

I've got next error 

```
 dryrun https://github.com/stfalcon-studio/ChatKit
Searching for devices...
Picked cannot
Found project in /var/folders/gc/l2qnrqyx237036ksp7rlj3cm0000gn/T/dryrun/stfalcon-studio/ChatKit...
HEAD is now at bd0df96 0.1.2 release
Fetching origin
Already on 'master'
Your branch is up-to-date with 'origin/master'.
From https://github.com/stfalcon-studio/ChatKit
 * branch            master     -> FETCH_HEAD
Already up-to-date.


======================================================

 Something went wrong while executing this:
  $ gradle wrap

======================================================
```

- _MacOS 10.12.3_
- _ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]_
- _dryrun 0.9.0_
- _java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)_

**Comment by cesarferreira** [comment]
Dryrun works in multi module projects, I tried that repository myself a week ago and it work great, just tried again and it also worked.

The problem was when it tried to run `gradle wrap` (not related to dryrun),

Maybe try and go to `/var/folders/gc/l2qnrqyx237036ksp7rlj3cm0000gn/T/dryrun/stfalcon-studio/ChatKit` and run `gradle wrap` to see in detail what failed.

**Comment by dEn13L** [comment]
Thank you for your answer!

I've done. First of all, I had not global gradle in my system) I installed 3.4, then I had to accept Android licences and finally got an error

```
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':chatkit'.
> Failed to notify project evaluation listener.
   > org/gradle/api/internal/component/Usage
``` 

So, I downgraded gradle to 2.14.1 and it works!

Issue can be closed, thanks!

**Comment by aldefy** [comment]
facing exact same - same chatkit lib , what do u recommend 
gradle --version

------------------------------------------------------------
Gradle 4.1-milestone-1
------------------------------------------------------------

Build time:   2017-06-20 17:05:46 UTC

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Mac OS X 10.12.5 x86_64

**Comment by cesarferreira** [comment]
This is not related to `dryrun` but it probably can be fixed if you run `brew install gradle`

**Comment by cesarferreira** [comment]
This is not related to `dryrun`, there's something wrong with that project as stated by @dEn13L
