### ISSUE TITLE
Error installing dryrun

### ISSUE THREAD

**Issue by 08carmelo** [cesarferreira/dryrun#91]
sudo gem install dryrun 安装失败啊。。。。环境：mac 10.11.3
ERROR:  Error installing dryrun:
ERROR: Failed to build gem native extension.
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h

**Comment by cesarferreira** [comment]
This is an issue with your ruby, not this gem

**Comment by cesarferreira** [comment]
btw: why SUDO?
And upgrade your ruby version
