### ISSUE TITLE
Invalid argument @ rb_sysopen (Errno::EINVAL)

### ISSUE THREAD

**Issue by madd86** [cesarferreira/dryrun#93]
Trying to run it on Windows 10.

* Installed Ruby 2.3.0

* Installed Java JDK 8

* Configured JAVA_HOME & ANDROID_HOME

* Installed dryrun successfully

Trying the following line:

`dryrun --debug git@github.com:cesarferreira/android-helloworld.git`

Results in the following:

```
Searching for devices...
Pick your device (1,2,3...):
0 -  03106697213e976b
1 -  emulator-5554
C:/Ruby23/lib/ruby/gems/2.3.0/gems/dryrun-0.9.0/lib/dryrun.rb:123:in `gets': Invalid argument @ rb_sysopen - git@github.com:cesarferreira/android-helloworld.git (Errno::EINVAL)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/dryrun-0.9.0/lib/dryrun.rb:123:in `gets'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/dryrun-0.9.0/lib/dryrun.rb:123:in `pick_device'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/dryrun-0.9.0/lib/dryrun.rb:168:in `call'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/dryrun-0.9.0/bin/dryrun:6:in `<top (required)>'
        from C:/Ruby23/bin/dryrun:22:in `load'
        from C:/Ruby23/bin/dryrun:22:in `<main>'
```

**EDIT:** The actual error is this:
(It seems as though the previous one was caused by having two devices)

```
 Something went wrong while executing this:
  $ git clone --depth 1 git@github.com:cesarferreira/android-helloworld.git C:/Users/matt/AppData/Local/Temp/dryrun/cesarferreira/android-helloworld
```

I know, you need to logs, trying to figure out how to access them, since it wasn't documented in the read me (that's an idea).

**Comment by cesarferreira** [comment]
Hey,
what happens if you try to run this command?

> git clone --depth 1 git@github.com:cesarferreira/android-helloworld.git C:/Users/matt/AppData/Local/Temp/dryrun/cesarferreira/android-helloworld
