### ISSUE TITLE
bash: dryrun: command not found

### ISSUE THREAD

**Issue by AlaaZarifa** [cesarferreira/dryrun#94]
- I'm running Windows 10
- I downloaded Ruby installer successfully
- I opened Ruby command prompt from search > MSYS2 MSYS
- I typed `dryrun https://github.com/cesarferreira/android-helloworld`

But it shows me this error
```
Alaa Sami MSYS ~
$ dryrun https://github.com/cesarferreira/android-helloworld
bash: dryrun: command not found
```
I tried to set the environment variable like this, but antoher error !

```
Alaa Sami@DESKTOP-16FQ38J MSYS ~
$ set %PATH%;

Alaa Sami@DESKTOP-16FQ38J MSYS ~
$ C:\Ruby24-x64\bin
bash: C:Ruby24-x64bin: command not found
```

any help !?

**Comment by cesarferreira** [comment]
did you install dryrun?

**Comment by AlaaZarifa** [comment]
oh, I did, but I solved this now, I wasn't installing the DevKit correctly 
after following the steps [here](https://forwardhq.com/help/installing-ruby-windows), it worked 👍 
 
why it takes so much time to launch the demo on the emulator?  like 5-10 min !? ⏲

**Comment by cesarferreira** [comment]
that's not on me, that's gradle, maybe your computer is slow 😄
