### ISSUE TITLE
Error that SDK directory does not exist, although it does

### ISSUE THREAD

**Issue by bizzguy** [cesarferreira/dryrun#95]
dryrun https://github.com/cesarferreira/android-helloworld
Searching for devices...
Picked emulator-5554
Found project in /var/folders/zv/m7p966v57psd4qt50jnp39b00000gn/T/dryrun/cesarferreira/android-helloworld...
HEAD is now at f106462 few tests more
Fetching origin
Already on 'master'
Your branch is up-to-date with 'origin/master'.
From https://github.com/cesarferreira/android-helloworld
 * branch            master     -> FETCH_HEAD
Already up-to-date.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> The SDK directory '~/Library/Android/sdk' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by bizzguy** [comment]
ANDROID_HOME is set and pointing to correct location

echo $ANDROID_HOME
~/Library/Android/sdk

**Comment by cesarferreira** [comment]
show me this output: `ls ~/Library/Android/sdk`

**Comment by cesarferreira** [comment]
I don't think you can use `~` in bash variables, look at mine:

```
❯ echo $ANDROID_HOME             
/Users/cesarferreira/Library/Android/sdk/
```

**Comment by bizzguy** [comment]
Thanks.  That was it.  I needed to put the full path name in ANDROID_HOME.
