### ISSUE TITLE
No such file or directory - /platform-tools/adb

### ISSUE THREAD

**Issue by mradzinski** [cesarferreira/dryrun#96]
Dryrun exception: 

```
Searching for devices...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `spawn': No such file or directory - /platform-tools/adb (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-0.9.0/lib/dryrun/dryrun_utils.rb:54:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-0.9.0/lib/dryrun/dryrun_utils.rb:46:in `run_adb'
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-0.9.0/lib/dryrun.rb:108:in `pick_device'
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-0.9.0/lib/dryrun.rb:168:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/dryrun-0.9.0/bin/dryrun:6:in `<top (required)>'
	from /usr/local/bin/dryrun:23:in `load'
	from /usr/local/bin/dryrun:23:in `<main>'
```

I do have $ANDROID_HOME set and ADB is working from the terminal

```
❯ echo $ANDROID_HOME
/Users/matias/Library/Android/sdk
```
```
~
❯ adb devices
List of devices attached
emulator-5554	device
```

```
~/Library/Android/sdk
❯ cd $ANDROID_HOME/platform-tools

~/Library/Android/sdk/platform-tools
❯ ls
NOTICE.txt        api               etc1tool          hprof-conv        package.xml       sqlite3
adb               dmtracedump       fastboot          lib               source.properties systrace
```

**Comment by mradzinski** [comment]
I ended up manually modifying the `dryrun.rb` file and hardcoding my `$ANDROID_HOME` path. Now it's compiling everything and working fine, which wouldn't be the case if `$ANDROID_HOME` wasn't exported properly (gradle would complain about not being able to find the env variable), so there's an obvious bug in the way you are getting the `$ANDROID_HOME` env variable which seems to be failing under certain scenarios (I'm using ZSH with iTerm2 on macOS Sierra, maybe that has something to do, no idea).

**Comment by cesarferreira** [comment]
I believe the problem is that you don't have the platform-tools path 

```

**Comment by cesarferreira** [comment]
export PATH=$PATH:/Users/cesarferreira/Library/Android/sdk/platform-tools/platform-tools
export PATH=$PATH:/Users/cesarferreira/Library/Android/sdk/platform-tools/tools

**Comment by cesarferreira** [comment]
Do you have this in your `~/.zshrc` ?
```
export PATH=$PATH:/Users/cesarferreira/Library/Android/sdk/platform-tools/platform-tools
export PATH=$PATH:/Users/cesarferreira/Library/Android/sdk/platform-tools/tools
```

**Comment by cesarferreira** [comment]
also check #84

**Comment by mladenrakonjac** [comment]
I needed to make **adb** global:
❯ echo 'export ANDROID_HOME=/Users/$USER/Library/Android/sdk' >> ~/.bash_profile                

~
❯ echo 'export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools' >> ~/.bash_profile

~
❯ source ~/.bash_profile
