### ISSUE TITLE
bad interpreter

### ISSUE THREAD

**Issue by athulcek** [cesarferreira/dryrun#99]
When i run the cmd i`m getting this 
-bash: /usr/local/bin/dryrun: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory

**Comment by cesarferreira** [comment]
There's seem to be an issue with your ruby https://www.google.co.uk/search?q=ruby%3A+bad+interpreter%3A+No+such+file+or+directory&oq=ruby%3A+bad+interpreter%3A+No+such+file+or+directory&aqs=chrome..69i57j69i58.174j0j1&sourceid=chrome&ie=UTF-8

**Comment by navyifanr** [comment]
@athulcek Do you solve the problem? I have the same problem with you.
